
/**
 * Module dependencies.
 */

var parse = require('co-body');
var render = require('../lib/render');

/**
 * Configure monk.
 */

var monk = require('monk');
var wrap = require('co-monk');
var db = monk('localhost/koaBlog');
var snaps = wrap(db.get('snaps'));

/**
 * Define routes
 */

var Routes = {};

/**
 * Render index html page.
 */

Routes.index = function *index() {
  this.body = yield render('index');
};

/**
 * Render page with snap given id.
 */

Routes.show = function *show() {
  // Decrement view in Snap.
  // If view = 0, delete tweet, snap.
  this.body = yield render('snap');
};

/**
 * Create a new snap.
 */

Routes.create = function *create() {
  console.log(this.request.body);

  if (!this.request.body) return;
  var body = this.request.body;

  // Save to Mongo:
  //   @property string id (should we use message id
  //   @property string url (absolute path to Twilio media)
  //   @property number views (start at 10?)
  //   @property string tweetId (generated by twitter, null as default)
  var snap = {
    id: body.MessageSid,
    url: body.MediaUrl0,
    views: 10,
    tweetId: null
  };

  // yield snaps.insert(snap);
  // yield tweet(snap);
};

/**
 * Expose `Routes`.
 */

module.exports = Routes;
